#!/usr/bin/env bash

set -e
echo_green () {
    echo -e "\033[92m$*\033[0m"
} 
                                                
echo_warning () {
    echo -e "\033[33mWarning: $*\033[0m"
}

BACKDIR="$HOME/.dotfiles_conflict"
mv_conflicts () {
   if [[ -f "$1" && ! -L "$1" ]]
   then
       echo_warning "$1 existing, causing conflicts"
       echo "The original file has been moved to $BACKDIR"
       mv "$1" "$BACKDIR"
   fi     
}

# backup conflicts files
[[ ! -d "$BACKDIR" ]] && mkdir "$BACKDIR"
mv_conflicts ~/.profile
mv_conflicts ~/.gitconfig
mv_conflicts ~/.bash_profile
mv_conflicts ~/.bashrc

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

echo_green "==> Install tmux plugins"
~/.tmux/plugins/tpm/bin/install_plugins &> /dev/null  

echo_green "==> Install vim plugins"
vim +PlugInstall +qall &> /dev/null 
# instal ycmd
if [[ ! -f "$HOME/.vim/plugged/youcompleteme/third_party/ycmd/ycm_core.so" ]]
then
    YCM_DIR="$HOME/.vim/plugged/youcompleteme"
    cd "$YCM_DIR"
    # if error: "python3.6m not installed" (e.g. in Ubuntu 16.04), run
    # sudo apt install libpython3.6-dev
    # if memory insufficient: dont instal clang: ./install.py
    ./install.py --clang-completer
fi 

echo_green "==> Setting up Gemini CLI"
bash "${BASEDIR}/agents/setup_gemiini_cli.sh"

echo_green "==> Setting up Claude Code"
bash "${BASEDIR}/agents/setup_claude_code.sh"

echo_green "Done!"
